// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbwGDNOeW93ng2qbUPzr-KIIotel8mHAc',
    appId: '1:822044033674:web:24631d1d84f190ff3d2373',
    messagingSenderId: '822044033674',
    projectId: 'carrygo-137f1',
    authDomain: 'carrygo-137f1.firebaseapp.com',
    databaseURL: 'https://carrygo-137f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrygo-137f1.firebasestorage.app',
    measurementId: 'G-8PS6BZXWR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC3g62n_-4p4uQ_uO1LP-Z5WBj-2Q1Ito',
    appId: '1:822044033674:android:adc4de704c174b023d2373',
    messagingSenderId: '822044033674',
    projectId: 'carrygo-137f1',
    databaseURL: 'https://carrygo-137f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrygo-137f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXI5gW15s29KFmtEUQBfr90ylc9FIYkw',
    appId: '1:822044033674:ios:0cc446b0da3850773d2373',
    messagingSenderId: '822044033674',
    projectId: 'carrygo-137f1',
    databaseURL: 'https://carrygo-137f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrygo-137f1.firebasestorage.app',
    iosClientId: '822044033674-7p036t8fq634e83ir39q9ue9vvd1fvcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.timepilotAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaXI5gW15s29KFmtEUQBfr90ylc9FIYkw',
    appId: '1:822044033674:ios:0cc446b0da3850773d2373',
    messagingSenderId: '822044033674',
    projectId: 'carrygo-137f1',
    databaseURL: 'https://carrygo-137f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrygo-137f1.firebasestorage.app',
    iosClientId: '822044033674-7p036t8fq634e83ir39q9ue9vvd1fvcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.timepilotAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbwGDNOeW93ng2qbUPzr-KIIotel8mHAc',
    appId: '1:822044033674:web:fc7b70c1331fc5043d2373',
    messagingSenderId: '822044033674',
    projectId: 'carrygo-137f1',
    authDomain: 'carrygo-137f1.firebaseapp.com',
    databaseURL: 'https://carrygo-137f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrygo-137f1.firebasestorage.app',
    measurementId: 'G-0VS61X2XE2',
  );
}
